### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by phipag** [GlueDev/laravel-stackdriver#10]
Hello,
I encounter the following error when enabling CloudTracing. The Laravel application is run in the official `php:7.4-apache` docker container. 
```
[2020-03-16 11:05:34] production.ERROR: Array and string offset access syntax with curly braces is deprecated {"exception":"[object] (ErrorException(code: 0): Array and string offset access syntax with curly braces is deprecated at /var/www/html/vendor/opencensus/opencensus/src/Trace/Propagator/CloudTraceFormatter.php:104)
[stacktrace]
#0 /var/www/html/vendor/composer/ClassLoader.php(444): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'Array and strin...', '/var/www/html/v...', 104, Array)
#1 /var/www/html/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/html/v...')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('OpenCensus\\\\Trac...')
#4 /var/www/html/vendor/opencensus/opencensus/src/Trace/Propagator/HttpHeaderPropagator.php(51): spl_autoload_call('OpenCensus\\\\Trac...')
#5 /var/www/html/vendor/opencensus/opencensus/src/Trace/Tracer.php(129): OpenCensus\\Trace\\Propagator\\HttpHeaderPropagator->__construct()
#6 /var/www/html/vendor/gluedev/laravel-stackdriver/src/Stackdriver.php(77): OpenCensus\\Trace\\Tracer::start(Object(OpenCensus\\Trace\\Exporter\\StackdriverExporter))
#7 /var/www/html/vendor/gluedev/laravel-stackdriver/src/StackdriverServiceProvider.php(23): GlueDev\\Laravel\\Stackdriver\\Stackdriver->startTracing()
#8 [internal function]: GlueDev\\Laravel\\Stackdriver\\StackdriverServiceProvider->boot()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->call(Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(839): Illuminate\\Foundation\\Application->bootProvider(Object(GlueDev\\Laravel\\Stackdriver\\StackdriverServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(GlueDev\\Laravel\\Stackdriver\\StackdriverServiceProvider), 17)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): array_walk(Array, Object(Closure))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#23 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#24 {main}
"}
```

**Comment by DiederikvandenB** [comment]
This is not an issue with this package, but with the underlying OpenCensus dependency.
https://github.com/census-instrumentation/opencensus-php/blob/master/src/Trace/Propagator/CloudTraceFormatter.php#L104

Please report the issue there.

**Comment by DiederikvandenB** [comment]
Someone seems to be working on this already:
https://github.com/census-instrumentation/opencensus-php/pull/254

**Comment by phipag** [comment]
Thanks for the update.
